// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxhrjzamxfzthsewmsee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4aHJqemFteGZ6dGhzZXdtc2VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NzY3NjcsImV4cCI6MjA1ODQ1Mjc2N30.eOgFq7XgKsUajt1-eVYE-YMHvgHIvVQDpkQxOkNX2Fk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);